### ISSUE TITLE
Implement "Login with Google"

### ISSUE THREAD

**Issue by troeger** [kubeportal/kubeportal-frontend#1]
- [x] Implement button with Google logo
- [x] Get OpenID client configuration from local config file / environment variables
- [x] Start OIDC auth flow when button is clicked, based on Vue.JS OIDC client library
- [x] Generate resp. forward resulting JWT token to be used when talking to the backend

**Comment by troeger** [comment]
Blocked by #2.

**Comment by kat-hi** [comment]
https://github.com/mejiamanuel57/vue-google-signin-button-directive
