### ISSUE TITLE
provide functionality to change primary email

### ISSUE THREAD

**Issue by kat-hi** [kubeportal/kubeportal-frontend#32]
blocked by https://github.com/kubeportal/kubeportal-frontend/issues/31

**Comment by kat-hi** [comment]
fyi: it is done but the api PATCH is missing. we have to wait for api v1.4.0 release

**Comment by troeger** [comment]
Blocked by https://github.com/kubeportal/kubeportal/issues/102

**Comment by kat-hi** [comment]
done https://github.com/kubeportal/kubeportal/pull/113
