### ISSUE TITLE
Vue3 upgrade

### ISSUE THREAD

**Issue by kat-hi** [kubeportal/kubeportal-frontend#37]
new features are pretty nice....
general: https://www.youtube.com/watch?v=A5cVyjrKx_Q
composition api: https://www.youtube.com/watch?v=bwItFdPt-6M (6:12)

**Comment by troeger** [comment]
Ok, you port that thing to TypeScript? Awesome ...

**Comment by kat-hi** [comment]
not sure. we could give it a try. this is out of my comfort zone. :+1:
