### ISSUE TITLE
Implement existing frontend views

### ISSUE THREAD

**Issue by troeger** [kubeportal/kubeportal-frontend#4]
API calls must be available from the mock implementation.

- [x] Welcome page
- [x] Config file page
- [x] Statistics page, separate API calls per single value, loading "lazily"

**Comment by kat-hi** [comment]
fyi and mind dump: I guess the last point is already solved by requesting the data when the welcome page was mounted. This does not work if one calls /statistics directly but in that case I will find some nice vuetify-wonderland-features.

**Comment by kat-hi** [comment]
it's done, besides the opened bugs and enhancements.
https://github.com/kubeportal/kubeportal-frontend/pull/10
