### ISSUE TITLE
Redirect for invalid URL

### ISSUE THREAD

**Issue by DenizCankurtaran** [kubeportal/kubeportal-frontend#52]
How about a redirect to the login screen, if an invalid URL is entered?

currently only a blank page is displayed

![Screenshot from 2020-10-13 21-17-34](https://user-images.githubusercontent.com/58952375/95905867-a8517480-0d99-11eb-9b8b-b23d1f1649ab.png)

**Comment by kat-hi** [comment]
vote +1
